name: Deploy Terraform with SPN

on: # The trigger configuration can be customized as needed.
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  ACTIONS_RUNNER_DEBUG: true
  ARM_CLIENT_ID: "${{ secrets.ARM_SPN_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_SPN_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
  TF_LOG: INFO

jobs:
  preview:
    runs-on: ubuntu-latest
    outputs:
      TFPLAN_EXITCODE: ${{ steps.tfplan.outputs.exitcode }}

    steps:
      - uses: actions/checkout@v3.5.0
        name: Checkout code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          terraform init -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}" -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}"

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: tfplan
        run: |
          terraform plan --detailed-exitcode -var storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -var storage_account_container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" || exit 0

  deploy:
    runs-on: ubuntu-latest
    needs: preview
    if: needs.preview.outputs.TFPLAN_EXITCODE == 2
    environment: production
    steps:
      - uses: actions/checkout@v3.5.0
        name: Checkout code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          terraform init -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}" -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}"

      - name: Terraform Apply
        run: |
          terraform apply --auto-approve -var storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -var storage_account_container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}"
